# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC20():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.driver.maximize_window()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC20(self):
    self.driver.get("https://chimmymeowspa.com//")
    self.driver.find_element(By.CSS_SELECTOR, "#menu-item-492 .menu-text").click()
    time.sleep(3)
    self.driver.find_element(By.LINK_TEXT, "Bạn chưa có tài khoản? Đăng ký ngay.").click()
    time.sleep(3)
    self.driver.find_element(By.ID, "user_login").send_keys("")
    self.driver.find_element(By.ID, "user_email").send_keys("")
    self.driver.find_element(By.ID, "user_pass").send_keys("")
    self.driver.find_element(By.ID, "user_confirm_password").send_keys("")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    time.sleep(3)
    elements = self.driver.find_elements(By.ID, "user_confirm_password-error")
    assert len(elements) > 0
  
